FROM php:7.4-fpm-alpine3.15

# Easy extension installer (with dependencies)
# https://github.com/mlocati/docker-php-extension-installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

# Install extensions
RUN install-php-extensions gmp rdkafka
