FROM renebakx/composer-php74:2.2.5

# Easy extension installer (with dependencies)
# https://github.com/mlocati/docker-php-extension-installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

# Install extensions
RUN install-php-extensions rdkafka
